# Generated by Django 3.0.7 on 2020-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Urgent'), ('2', 'Important'), ('3', 'Low'), ('4', 'Medium'), ('5', 'When possible')], default='Medium', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
