# Generated by Django 3.0.7 on 2020-06-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200623_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['event_date']},
        ),
    ]
